export const mockVideos = [
  {
    id: '1',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    creator: 'educator1',
    description: 'Learn React Native in 60 seconds',
    likes: '10.2k',
    comments: 234,
    shares: 42,
  },
  {
    id: '2',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    creator: 'teacher2',
    description: 'Master this one skill to 10x your productivity',
    likes: '5.8k',
    comments: 89,
    shares: 23,
  },
  {
    id: '3',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    creator: 'coach3',
    description: 'The secret to learning anything fast',
    likes: '2.1k',
    comments: 45,
    shares: 12,
  },
  {
    id: '4',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    creator: 'educator4',
    description: 'Why you should learn this TODAY',
    likes: '15.3k',
    comments: 567,
    shares: 89,
  },
  {
    id: '5',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    creator: 'teacher5',
    description: 'Mind-blowing productivity hack',
    likes: '8.7k',
    comments: 234,
    shares: 56,
  },
  {
    id: '6',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    creator: 'coach6',
    description: 'This changed everything for me',
    likes: '12.4k',
    comments: 345,
    shares: 78,
  },
  {
    id: '7',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    creator: 'educator7',
    description: 'Stop making this mistake',
    likes: '9.1k',
    comments: 156,
    shares: 34,
  },
  {
    id: '8',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    creator: 'teacher8',
    description: 'The truth about success nobody tells you',
    likes: '18.9k',
    comments: 678,
    shares: 123,
  },
  {
    id: '9',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    creator: 'coach9',
    description: 'How I learned this in 30 days',
    likes: '6.5k',
    comments: 123,
    shares: 29,
  },
  {
    id: '10',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    creator: 'educator10',
    description: 'Game-changing advice for beginners',
    likes: '14.2k',
    comments: 456,
    shares: 91,
  },
  // Repeat pattern for videos 11-50
  {
    id: '11',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    creator: 'educator11',
    description: 'Advanced techniques explained simply',
    likes: '11.3k',
    comments: 289,
    shares: 67,
  },
  {
    id: '12',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    creator: 'teacher12',
    description: 'Why most people fail at this',
    likes: '7.8k',
    comments: 134,
    shares: 41,
  },
  {
    id: '13',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    creator: 'coach13',
    description: 'The framework that actually works',
    likes: '13.6k',
    comments: 423,
    shares: 85,
  },
  {
    id: '14',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    creator: 'educator14',
    description: 'Unlock your potential with this method',
    likes: '9.9k',
    comments: 267,
    shares: 53,
  },
  {
    id: '15',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    creator: 'teacher15',
    description: 'Common myths debunked',
    likes: '16.7k',
    comments: 589,
    shares: 112,
  },
  {
    id: '16',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    creator: 'coach16',
    description: 'Step-by-step tutorial for beginners',
    likes: '5.4k',
    comments: 98,
    shares: 22,
  },
  {
    id: '17',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    creator: 'educator17',
    description: 'What I wish I knew earlier',
    likes: '12.8k',
    comments: 356,
    shares: 74,
  },
  {
    id: '18',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    creator: 'teacher18',
    description: 'The fastest way to improve',
    likes: '8.3k',
    comments: 178,
    shares: 39,
  },
  {
    id: '19',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    creator: 'coach19',
    description: 'Pro tips nobody shares',
    likes: '17.1k',
    comments: 623,
    shares: 134,
  },
  {
    id: '20',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    creator: 'educator20',
    description: 'This will blow your mind',
    likes: '10.5k',
    comments: 298,
    shares: 61,
  },
  {
    id: '21',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    creator: 'educator21',
    description: 'Essential knowledge for 2025',
    likes: '14.9k',
    comments: 478,
    shares: 96,
  },
  {
    id: '22',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    creator: 'teacher22',
    description: 'Simple hack for massive results',
    likes: '6.7k',
    comments: 145,
    shares: 31,
  },
  {
    id: '23',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    creator: 'coach23',
    description: 'Transform your skills overnight',
    likes: '11.2k',
    comments: 334,
    shares: 69,
  },
  {
    id: '24',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    creator: 'educator24',
    description: 'The complete guide you need',
    likes: '15.8k',
    comments: 512,
    shares: 103,
  },
  {
    id: '25',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    creator: 'teacher25',
    description: 'Secrets from industry experts',
    likes: '9.4k',
    comments: 223,
    shares: 47,
  },
  {
    id: '26',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    creator: 'coach26',
    description: 'Level up your game today',
    likes: '13.1k',
    comments: 389,
    shares: 81,
  },
  {
    id: '27',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    creator: 'educator27',
    description: 'Why this matters more than ever',
    likes: '7.6k',
    comments: 167,
    shares: 36,
  },
  {
    id: '28',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    creator: 'teacher28',
    description: 'Master class in 60 seconds',
    likes: '18.3k',
    comments: 645,
    shares: 129,
  },
  {
    id: '29',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    creator: 'coach29',
    description: 'Breakthrough method revealed',
    likes: '10.9k',
    comments: 312,
    shares: 64,
  },
  {
    id: '30',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    creator: 'educator30',
    description: 'Change your perspective on learning',
    likes: '12.6k',
    comments: 367,
    shares: 76,
  },
  {
    id: '31',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    creator: 'educator31',
    description: 'The science behind success',
    likes: '8.8k',
    comments: 198,
    shares: 43,
  },
  {
    id: '32',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    creator: 'teacher32',
    description: 'Practical tips for real results',
    likes: '16.4k',
    comments: 534,
    shares: 107,
  },
  {
    id: '33',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    creator: 'coach33',
    description: 'What successful people do differently',
    likes: '5.9k',
    comments: 112,
    shares: 26,
  },
  {
    id: '34',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    creator: 'educator34',
    description: 'Fundamentals everyone should know',
    likes: '14.7k',
    comments: 445,
    shares: 89,
  },
  {
    id: '35',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    creator: 'teacher35',
    description: 'Next-level strategies explained',
    likes: '11.5k',
    comments: 278,
    shares: 58,
  },
  {
    id: '36',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    creator: 'coach36',
    description: 'Revolutionary approach to learning',
    likes: '9.7k',
    comments: 245,
    shares: 51,
  },
  {
    id: '37',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    creator: 'educator37',
    description: 'Optimize your learning path',
    likes: '13.9k',
    comments: 401,
    shares: 83,
  },
  {
    id: '38',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    creator: 'teacher38',
    description: 'Expert insights you need to hear',
    likes: '7.2k',
    comments: 156,
    shares: 34,
  },
  {
    id: '39',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    creator: 'coach39',
    description: 'Powerful lesson in under a minute',
    likes: '17.6k',
    comments: 589,
    shares: 118,
  },
  {
    id: '40',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    creator: 'educator40',
    description: 'Hidden gems of knowledge',
    likes: '10.1k',
    comments: 267,
    shares: 55,
  },
  {
    id: '41',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    creator: 'educator41',
    description: 'Critical thinking skills tutorial',
    likes: '15.2k',
    comments: 489,
    shares: 98,
  },
  {
    id: '42',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    creator: 'teacher42',
    description: 'Accelerate your growth today',
    likes: '6.3k',
    comments: 134,
    shares: 29,
  },
  {
    id: '43',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    creator: 'coach43',
    description: 'Wisdom from years of experience',
    likes: '12.9k',
    comments: 378,
    shares: 78,
  },
  {
    id: '44',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    creator: 'educator44',
    description: 'Transform how you think about this',
    likes: '8.5k',
    comments: 201,
    shares: 44,
  },
  {
    id: '45',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    creator: 'teacher45',
    description: 'Everything you need to know',
    likes: '19.1k',
    comments: 712,
    shares: 142,
  },
  {
    id: '46',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    creator: 'coach46',
    description: 'Innovative learning technique',
    likes: '11.8k',
    comments: 323,
    shares: 67,
  },
  {
    id: '47',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    creator: 'educator47',
    description: 'Quick wins for fast learners',
    likes: '9.3k',
    comments: 234,
    shares: 49,
  },
  {
    id: '48',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    creator: 'teacher48',
    description: 'Deep dive into the essentials',
    likes: '14.5k',
    comments: 456,
    shares: 92,
  },
  {
    id: '49',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    creator: 'coach49',
    description: 'Practical wisdom for everyday use',
    likes: '7.9k',
    comments: 189,
    shares: 41,
  },
  {
    id: '50',
    url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    creator: 'educator50',
    description: 'Final lesson that ties it all together',
    likes: '16.8k',
    comments: 567,
    shares: 114,
  },
];
